theme: practical-club-website-template
title: PH-ormula
description: Website for Shanghai Pinghe School Math Club
url: "https://ph-ormula.github.io"

minima:
  skin: auto
  nav_pages:
    - index.md
    - math-talks.md
    - resources.md
    - phlogicians.md
    - phcubers.md

plugins:
  - jekyll-seo-tag
  - jekyll-feed

kramdown:
  math_engine: mathjax
  input: GFM

exclude:
  - README.md
  - GEMINI.md
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .bundle/
  - Gemfile.lock

keep-files:
  - resources/
